# Generated by Django 3.0.1 on 2020-10-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pet_name',
            field=models.CharField(default=10, max_length=20),
        ),
    ]
