# Generated by Django 3.0.1 on 2020-11-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mird', '0004_auto_20201101_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
